# Usa una imagen base de Python
FROM python:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos al contenedor
COPY app.py .

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
